name: Basic Workflow
# run-name: ${{ github.triggering_actor }} is playing with GitHub Actions

on:
    push:
      branches:
        - main
      paths-ignore: 
        - '.github/workflows/**'
      
    workflow_dispatch: 
    
jobs:
  # Job 1
  checkout_job:
    name: Checkout Job
    runs-on: ubuntu-latest
    env:
      artpath: ${{ github.workspace }}/artifacts

    steps: 
      - name: checkout git repo
        uses: actions/checkout@v4
    
      - name: list checked out files and commits
        env:
          gitlog: "${{ env.artpath }}/gitlog.txt"
        # Output file info to artifact text file
        run: |
          mkdir -p "${{ env.artpath }}"
          mkdir -p "tmp"

          printf "** Current Commit **\n" > "${{ env.gitlog }}"
          git log -1 --oneline >> "${{ env.gitlog }}"
          printf "\n\n** Workspace Size Info **\n" >> "${{ env.gitlog }}"
          du -sh $(ls -A) | sort -hr >> "${{ env.gitlog }}"
          printf "\n\n** Workspace Files **\n" >> "${{ env.gitlog }}"
          tree -a >> "${{ env.gitlog }}"

      - name: upload text-file artifacts
        uses: actions/upload-artifact@v3
        with:
          name: text_files
          path: ${{ env.artpath }}/**/*.txt
      

  # Job 2
  basic_job:
    name: Basic Job
    runs-on: ubuntu-latest
    needs: checkout_job
    env:
      tmppath: ${{ github.workspace }}/tmp

    steps:
        - name: update apt packages
          if: github.event_name == 'push'
          run: |
            sudo apt-get update
          
        - name: install doas
          if: github.event_name == 'push'
          run: |
            sudo apt install -y doas
          
        - name: test workflow_dispatch
          if: github.event_name == 'workflow_dispatch'
          run: |
            echo "This workflow was triggered manually."

        # Workspace Item Count
        - name: make tmp dir
          run: mkdir -p "${{ env.tmppath }}"

        - name: download gitlog artifact
          uses: actions/download-artifact@v3
          with:
            name: text_files
            path: ${{ env.tmppath }}

        - name: print workspace item-count summary
          env:
            gitlog: "${{ env.tmppath }}/gitlog.txt"
          run: |
            printf "\n** Workspace Item-Count Summary **\n"
            grep -E "^[0-9]+ directories, [0-9]+ files$" "${{ env.gitlog }}" | tail -1
          