name: Basic Workflow
# run-name: ${{ github.triggering_actor }} is playing with GitHub Actions

on:
    push:
      branches:
        - main
      paths-ignore: 
        - '.github/workflows/**'
      
    workflow_dispatch: 
    
jobs:
  checkout_job:
    name: Checkout Job
    runs-on: ubuntu-latest
    env:
      artpath: ${{ github.workspace }}/artifacts

    steps: 
      - name: checkout git repo
        uses: actions/checkout@v4
    
      - name: list checked out files and commits
        env:
          gitlog: "${{ env.artpath }}/gitlog.txt"
        run: |
          mkdir -p "${{ env.artpath }}"
          git log --oneline > "${{ env.gitlog }}"
          ls -la >> "${{ env.gitlog }}"

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/**/*
      

  basic_job:
    name: Basic Job
    runs-on: ubuntu-latest
    needs: checkout_job

    steps:
        - name: update apt packages
          if: github.event_name == 'push'
          run: |
            sudo apt-get update
          
        - name: install doas
          if: github.event_name == 'push'
          run: |
            sudo apt install -y doas
          
        - name: test workflow_dispatch
          if: github.event_name == 'workflow_dispatch'
          run: |
            echo "This workflow was triggered manually."