name: Basic Workflow

on:
    push:
      branches:
        - main
      paths-ignore: 
        - '.github/workflows/**'
    
    workflow_dispatch: 


jobs:
    basic_job:
        name: Basic Job
        runs-on: ubuntu-latest
    
        steps:
            - name: update apt packages
              if: github.event_name == 'push'
              run: |
                sudo apt-get update
              
            - name: install doas
              if: github.event_name == 'push'
              run: |
                sudo apt install -y doas
              
            - name: test workflow_dispatch
              if: github.event_name == 'workflow_dispatch'
              run: |
                echo "This workflow was triggered manually."