name: "Basic Workflow"

on:
    push:
      branches:
      - main

jobs:
    basic_job:
        name: Basic Job
        runs-on: ubuntu-latest
    
        steps:
            - name: update apt packages
              run: |
                apt-get update
            
            - name: install doas
              run: |
                apt install -y doas

        
