name: Pull Request – Test Code

on:
    pull_request: 
      branches: [ main ]
      
    # workflow_dispatch: 
    
jobs:
    review:
        name: Review PR
        runs-on: ubuntu-latest
        steps:
            - name: checkout git repo
              uses: actions/checkout@v4
            - name: run python tests
              working-directory: "${{ github.workspace }}/app/test"
              run: pytest